{{- if and .Values.secret.enabled (or .Values.secretEnv .Values.secretData) }}
{{- $annotations := mergeOverwrite (deepCopy (default (dict) .Values.app.annotations)) (default (dict) .Values.secret.annotations) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app-chart.secretName" . }}
  namespace: {{ include "app-chart.namespace" . }}
  labels:
    {{- include "app-chart.labels" . | nindent 4 }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: {{ .Values.secret.type }}
stringData:
  {{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- range $key, $value := .Values.secretData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
