{{- if .Values.serviceAccount.create }}
{{- $annotations := mergeOverwrite (deepCopy (default (dict) .Values.app.annotations)) (default (dict) .Values.serviceAccount.annotations) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app-chart.serviceAccountName" . }}
  namespace: {{ include "app-chart.namespace" . }}
  labels:
    {{- include "app-chart.labels" . | nindent 4 }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
