{{- if and .Values.configMap.enabled .Values.config }}
{{- $annotations := mergeOverwrite (deepCopy (default (dict) .Values.app.annotations)) (default (dict) .Values.configMap.annotations) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app-chart.configMapName" . }}
  namespace: {{ include "app-chart.namespace" . }}
  labels:
    {{- include "app-chart.labels" . | nindent 4 }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
