app:
  name: app
  namespace: default

replicaCount: 1

image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent

container:
  port: 8080

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  className: traefik
  host: app.example.com
  path: /

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
